PataGift/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
                       url(r'^$', 'PataGift.views.index', name='index'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^pata_gift/', include('pata_gift.urls')),
                       url(r'^search/', include('haystack.urls'),)
                       )

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

pata_gift/urls.py
from django.conf.urls import patterns, url
from pata_gift.views import *

urlpatterns = patterns('',
                       url(r'^register/$', register, name='register'),
                       url(r'^login/$', user_login, name='login'),
                       url(r'^logout/$', user_logout, name='logout'),
                       url(r'^my-account/$', my_account, name='my_account'),
                       url(r'^create-product-step-1/(?P<category_id>[0-9]+)/$', create_product_step_1,
                           name='create_product_step_1'),
                       url(r'^create-product-step-2/(?P<product_id>[0-9]+)/$', create_product_step_2,
                           name='create_product_step_2'),
                       url(r'^create-product-step-3/(?P<product_id>[0-9]+)/$', create_product_step_3,
                           name='create_product_step_3'),
                       url(r'^reg_form_error/$', reg_form_error, name='reg_form_error'),
                       url(r'^product_details/(?P<product_id>[0-9]+)/$', product_details,
                           name='product_details'),
                       url(r'^wedding-gifts/$', wedding_gift, name='wedding_gift'),
                       url(r'^love-gifts/$', love_gift, name='love_gift'),
                       url(r'^birthday-gifts/$', birthday_gift, name='birthday_gift'),
                       url(r'^anniversary-gifts/$', anniversary_gift, name='anniversary_gift'),
                       url(r'^graduation-gifts/$', graduation_gift, name='graduation_gift'),
                       url(r'^edit/(?P<product_id>\d+)/$', edit_product, name='edit_product'),
                       url(r'^edit-profile/$', edit_profile, name='edit_profile'),
                       url(r'^edit_product_location/(?P<product_id>\d+)/$', edit_product_location,
                           name='edit_product_location'),
                       url(r'^delete/(?P<product_id>\d+)/$', delete_product, name='delete_product'),
                       url(r'^search/$', search_product, name='search'),
                       url(r'^profile-preview/$', profile_preview, name='profile_preview'),

                       )

pata_gift/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from extended_choices import Choices


class Trader(models.Model):
    user = models.OneToOneField(User)
    trader_phone_number = PhoneNumberField()
    trader_website = models.URLField(blank=True)

    def __str__(self):
        return self.user.first_name


class ProductCategory(models.Model):
    product_category = models.CharField(blank=False, max_length=128)

    def __str__(self):
        return self.product_category


class Product(models.Model):

    LOCATION_STATES = Choices(
        ('LOCATION_NOT_ADDED', 0, 'Location not added'),
        ('LOCATION_ADDED', 1, 'Location added')
    )

    IMAGES_STATES = Choices(
        ('IMAGES_NOT_ADDED', 0, 'Images not added'),
        ('IMAGES_ADDED', 1, 'Images added')
    )
    EDIT_STATES = Choices(
        ('NOT_EDITED', 0, 'Not edited'),
        ('EDITED_ONCE', 1, 'Edited once'),
        ('EDITED_TWICE', 2, 'Edited Twice'),
        ('EDITED_THRICE', 3, 'Edited Thrice'),
    )

    product_trader = models.ForeignKey(Trader)
    product_category = models.ForeignKey(ProductCategory)
    product_name = models.CharField(max_length=128, blank=False)
    product_price = models.IntegerField(default=0)
    product_image = models.ImageField()
    product_quantity = models.IntegerField()
    date_posted = models.DateTimeField(auto_now_add=True)
    location_state = models.SmallIntegerField(choices=LOCATION_STATES, default=LOCATION_STATES.LOCATION_NOT_ADDED)
    image_state = models.SmallIntegerField(choices=IMAGES_STATES, default=IMAGES_STATES.IMAGES_NOT_ADDED)
    edited_state = models.SmallIntegerField(choices=EDIT_STATES, default=EDIT_STATES.NOT_EDITED)

    def __str__(self):
        return self.product_name

    class Meta:
        ordering = ['-date_posted']


class ProductImage(models.Model):
    EDIT_STATES = Choices(
        ('NOT_EDITED', 0, 'Not edited'),
        ('EDITED_ONCE', 1, 'Edited once'),
        ('EDITED_TWICE', 2, 'Edited Twice'),
        ('EDITED_THRICE', 3, 'Edited Thrice'),
    )
    product_name = models.ForeignKey(Product)
    product_image_1 = models.ImageField(blank=False)
    product_image_2 = models.ImageField(blank=True, null=True)
    product_image_3 = models.ImageField(blank=True, null=True)
    product_image_4 = models.ImageField(blank=True, null=True)
    product_image_5 = models.ImageField(blank=True, null=True)
    edited_state = models.SmallIntegerField(choices=EDIT_STATES, default=EDIT_STATES.NOT_EDITED)

    def __str__(self):
        return self.product_name.product_name


class ProductLocation(models.Model):
    EDIT_STATES = Choices(
        ('NOT_EDITED', 0, 'Not edited'),
        ('EDITED_ONCE', 1, 'Edited once'),
        ('EDITED_TWICE', 2, 'Edited Twice'),
        ('EDITED_THRICE', 3, 'Edited Thrice'),)

    product_details = models.ForeignKey(Product)
    trader_main_city = models.CharField(max_length=128, blank=False)
    trader_sub_area = models.CharField(max_length=128, blank=False)
    trader_street = models.CharField(max_length=128, blank=False)
    trader_physical_location = models.CharField(max_length=128, blank=False)
    edited_state = models.SmallIntegerField(choices=EDIT_STATES, default=EDIT_STATES.NOT_EDITED)

    def __str__(self):
        return self.trader_main_city

PataGift/views.py
from django.shortcuts import render
from pata_gift.models import ProductCategory, Trader


def index(request):
    product_category = ProductCategory.objects.all()
    category_column = ProductCategory.objects.all()[:3]
    product_trader = Trader.objects.all()
    wedding_gifts = ProductCategory.objects.get(pk=5)
    love_gifts = ProductCategory.objects.get(pk=6)
    birthday_gifts = ProductCategory.objects.get(pk=7)
    anniversary_gifts = ProductCategory.objects.get(pk=8)
    graduation_gifts = ProductCategory.objects.get(pk=9)

    context_dic = {'product_categories': product_category,
                   'category_columns': category_column,
                   'traders': product_trader,
                   'wedding_gifts': wedding_gifts,
                   'love_gifts': love_gifts,
                   'birthday_gifts': birthday_gifts,
                   'anniversary_gifts': anniversary_gifts,
                   'graduation_gifts': graduation_gifts
                   }

    return render(request, 'pata_gift/index.html', context_dic)

pata_gift/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponseRedirect
from pata_gift.forms import *
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages
from django.core.urlresolvers import reverse


def register(request):
    
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        trader_form = TraderForm(request.POST, request.FILES)
        if User.objects.filter(email=request.POST['email']).exists():
            messages.warning(request, 'Sorry, the email address you have typed is already in use')
            return render(request, 'pata_gift/register.html', {'user_form': user_form,
                                                               'trader_form': trader_form, })
        if Trader.objects.filter(trader_phone_number=request.POST['trader_phone_number']).exists():
            messages.warning(request, 'Sorry, the phone number you have typed is already in use')
            return render(request, 'pata_gift/register.html', {'user_form': user_form,
                                                               'trader_form': trader_form, })
        password1 = request.POST['password']
        password2 = request.POST['password_confirmation']
        if password1 != password2:
            password_error = "Password didn't match"
            return render(request, 'pata_gift/register.html', {'user_form': user_form,
                                                               'trader_form': trader_form,
                                                               'password_error': password_error})

        if user_form.is_valid() and trader_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            worker = trader_form.save(commit=False)
            worker.user = user
            worker.save()

            user_form = UserForm()
            trader_form = TraderForm()
            messages.info(request, 'Congratulations! your account has been created and activated')

            return HttpResponseRedirect(reverse('register'), {'user_form': user_form,
                                                              'trader_form': trader_form})
        else:
            user_form = UserForm(request.POST)
            trader_form = TraderForm(request.POST)
            return render(request, 'pata_gift/register.html', {'user_form': user_form,
                                                               'trader_form': trader_form})
    else:
        user_form = UserForm()
        trader_form = TraderForm()

        return render(request, 'pata_gift/register.html', {'user_form': user_form,
                                                           'trader_form': trader_form})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect('/')
            else:
                error_msg = "Your account is not active. Kindly contact " \
                            "the system admin: admin@patagift.com"
                return render(request, 'pata_gift/login.html', {'error_msg': error_msg, })

        else:
            invalid_details = "You entered INVALID credentials. Kindly try again"

            return render(request, 'pata_gift/login.html', {'invalid_details': invalid_details, })

    else:
        return render(request, 'pata_gift/login.html', {})


@login_required
def user_logout(request):
    logout(request)

    return HttpResponseRedirect('/')


def my_account(request):
    category_column = ProductCategory.objects.all()[:3]
    product_trader = Trader.objects.all()
    wedding_gifts = ProductCategory.objects.get(pk=5)
    love_gifts = ProductCategory.objects.get(pk=6)
    birthday_gifts = ProductCategory.objects.get(pk=7)
    anniversary_gifts = ProductCategory.objects.get(pk=8)
    graduation_gifts = ProductCategory.objects.get(pk=9)

    wedding_category = ProductCategory.objects.get(pk=5)
    love_category = ProductCategory.objects.get(pk=6)
    birthday_category = ProductCategory.objects.get(pk=7)
    anniversary_category = ProductCategory.objects.get(pk=8)
    graduation_category = ProductCategory.objects.get(pk=9)
    try:
        trader = Trader.objects.get(user=request.user)
    except Trader.DoesNotExist:
        trader = None
    my_ads = Product.objects.filter(product_trader_id=trader.id).count()
    if trader:
        ads = Product.objects.filter(product_trader_id=trader.id)
        latest_ad = Product.objects.filter(product_trader_id=trader.id).first()
        if latest_ad:
            pass
        else:

            return render(request, 'pata_gift/my-account.html', {'ads': ads,
                                                                 'wedding_category': wedding_category,
                                                                 'love_category': love_category,
                                                                 'birthday_category': birthday_category,
                                                                 'anniversary_category': anniversary_category,
                                                                 'graduation_category': graduation_category,
                                                                 'my_ads': my_ads,
                                                                 'love_gifts': love_gifts,
                                                                 'wedding_gifts': wedding_gifts,
                                                                 'birthday_gifts': birthday_gifts,
                                                                 'anniversary_gifts': anniversary_gifts,
                                                                 'graduation_gifts': graduation_gifts}, )
    else:
        return HttpResponseRedirect('login')

    return render(request, 'pata_gift/my-account.html', {'ads': ads, 'latest': latest_ad,
                                                         'wedding_category': wedding_category,
                                                         'love_category': love_category,
                                                         'birthday_category': birthday_category,
                                                         'anniversary_category': anniversary_category,
                                                         'graduation_category': graduation_category,
                                                         'my_ads': my_ads,
                                                         'love_gifts': love_gifts,
                                                         'wedding_gifts': wedding_gifts,
                                                         'birthday_gifts': birthday_gifts,
                                                         'anniversary_gifts': anniversary_gifts,
                                                         'graduation_gifts': graduation_gifts}, )


@login_required
def create_product_step_1(request, category_id):
    categories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, pk=category_id)

    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES)

        if product_form.is_valid():
            product = product_form.save(commit=False)
            category = ProductCategory.objects.get(product_category=category)
            trader = Trader.objects.get(user=request.user)
            product.product_trader = trader
            product.product_category_id = category.id
            if 'product_image' in request.FILES:
                product.product_image = request.FILES['product_image']
                product.save()
            else:
                messages.warning(request, 'Please choose an image file')
                return render(request, 'pata_gift/create-product-step-1.html', {'product_form': product_form})
            return HttpResponseRedirect(reverse('my_account'))
        else:
            print(product_form.errors)
            return render(request, 'pata_gift/create-product-step-1.html', {'product_form': product_form})
    else:
        product_form = ProductForm()

        return render(request, 'pata_gift/create-product-step-1.html', {'product_form': product_form,
                                                                        'categories': categories})


def create_product_step_2(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if product.location_state == 1:
        return HttpResponseRedirect(reverse('my_account'),)

    if request.method == 'POST':
        product_location_form = ProductLocationForm(request.POST)

        if product_location_form.is_valid():
            product_location = product_location_form.save(commit=False)
            product_location.product_details = product
            product_location.save()
            product.location_state = 1
            product.save()

            return HttpResponseRedirect(reverse('my_account'))
        else:
            return render(request, 'pata_gift/create-product-step-2.html',
                          {'product_location_form': product_location_form})
    else:
        product_location_form = ProductLocationForm()
        return render(request, 'pata_gift/create-product-step-2.html',
                      {'product_location_form': product_location_form})


def create_product_step_3(request, product_id):

    product = get_object_or_404(Product, pk=product_id)
    if product.image_state == 1:
        return HttpResponseRedirect(reverse('my_account'),)

templates/pata_gift/ajax_search.html
{% if gifts_by_name.count > 0 %}

{% for gift in gifts_by_name %}
<li><a href="{% url 'product_detials' %}" >{{ gift.product_name }}</a></li>

{% endif %}

templates/pata_gift/birthday.html
{% extends 'base2.html' %}
{% load staticfiles %}
{% block search %}
<div class="container">
	<div class="row">
        <ul class="nav nav-tabs">
            <li role="presentation" ><a href="{% url 'index' %}"><i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;Home</a></li>

              <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gifts in other categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
               <li class="active"><a href="{% url 'wedding_gift' %}" >{{ wedding_gifts }}</a></li>
               <li role="separator" class="divider"></li>
            <li><a href="{% url 'love_gift' %}" >{{ love_gifts }}</a></li>
               <li role="separator" class="divider"></li>
            <li><a href="{% url 'birthday_gift' %}" >{{ birthday_gifts }}</a></li>
               <li role="separator" class="divider"></li>

           <li><a href="{% url 'anniversary_gift' %}" >{{ anniversary_gifts }}</a></li>
               <li role="separator" class="divider"></li>
            <li><a href="{% url 'graduation_gift' %}" >{{ graduation_gifts }}</a></li>
          </ul>
        </li>

      </ul>
	</div>
</div>
{% endblock search %}
{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
           <div class="col-sm-3 header-bg slider-height">

	<div class="row">
        <div class="col-sm-12">
            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    {% csrf_token %}
                    <input type="text" class="form-control input-lg" placeholder="Search e.g flowers" id="search" name="search" />
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="button">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>

                </div>

            </div>
            <div class="" id="search-results">

                </div>
        </div>
	</div>
<hr><br>
            <div class="col-sm-12 ">
                <div id="myCarousel" class="carousel slide " data-ride="carousel">
                      <!-- Indicators -->
                      <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                        <li data-target="#myCarousel" data-slide-to="3"></li>
                        <li data-target="#myCarousel" data-slide-to="4"></li>
                      </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">

      <div class="item active">
      <img src="{% static 'images/mug.jpg' %}" height=250 width=100% />
      <div class="carousel-caption">
        <h3>birthday gifts</h3>

      </div>
    </div>

    <div class="item">
      <img src="{% static 'images/love.jpg' %}" alt="love" height=250 width=100% />
      <div class="carousel-caption">
        <h3>Love</h3>

      </div>
    </div>
      <div class="item">
      <img src="{% static 'images/love.jpg' %}" alt="love" height=250 width=100% />
      <div class="carousel-caption">
        <h3>Love</h3>

      </div>
    </div>

    <div class="item">
      <img src="{% static 'images/pata_gift.png' %}" alt="birthday">
      <div class="carousel-caption">
        <h3>Birthday</h3>

      </div>
    </div>

    <div class="item">
      <img src="{% static 'images/pata_gift.png' %}" alt="graduation">
      <div class="carousel-caption">
        <h3>graduation</h3>

      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div></div></div>

           <div class="col-sm-9" id="birthday-items">
               <div class="h4 row-centered">birthday Gifts on Sale! Check out the deals</div><br>

                {% for product in birthday_gifts.product_set.all %}

               <div class="col-sm-12 item-listing upload-product-bg text-info text-center">

                        <div class="col-sm-2 col-centered">Item:&nbsp;&nbsp;&nbsp;{{ product.product_name }}<br>
                            Price:&nbsp;&nbsp;<b>Ksh.</b>&nbsp;&nbsp;{{ product.product_price }}</div>
                        <div class="col-sm-2 row-centered"><a data-overlay-trigger href="{% url 'product_details' product.id %}" >
                            <img class="img img-circle" src="{{ product.product_image.url }}" height="75" width="75"></a></div>
                       <div class="col-sm-4 ">
                           Call&nbsp;&nbsp; |&nbsp;&nbsp;Text &nbsp;&nbsp;|&nbsp;&nbsp; Whatsapp<br>

                         {{ product.product_trader }}<br>
                        {{ product.product_trader.trader_phone_number }}
                       </div>
                        <div class="col-sm-2 col-centered">{{ product.date_posted }}</div>
                        <div class="col-sm-2 col-centered">Quantity<br>
                            {% if product.product_quantity > 1 %}
                            {{ product.product_quantity }} &nbsp;&nbsp;&nbsp;{{ product.product_name|pluralize }}
                            {% else %}
                            {{ product.product_quantity }} &nbsp;&nbsp;&nbsp;{{ product.product_name }}
                            {% endif %}

                        </div>
               </div>
            {% endfor %}

           </div>

        </div>

    </div>

</div>

{% endblock content %}

templates/pata_gift/my-account.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">

        <ul class="nav nav-tabs">
            <li role="presentation" ><a href="{% url 'index' %}"><i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;Home</a></li>

              <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gifts in Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
               <li class="active"><a href="{% url 'wedding_gift' %}" >{{ wedding_gifts }}</a></li>
               <li role="separator" class="divider"></li>
            <li><a href="{% url 'love_gift' %}" >{{ love_gifts }}</a></li>
               <li role="separator" class="divider"></li>
            <li><a href="{% url 'birthday_gift' %}" >{{ birthday_gifts }}</a></li>
               <li role="separator" class="divider"></li>

           <li><a href="{% url 'anniversary_gift' %}" >{{ anniversary_gifts }}</a></li>
               <li role="separator" class="divider"></li>
            <li><a href="{% url 'graduation_gift' %}" >{{ graduation_gifts }}</a></li>
          </ul>
        </li>
            <button class="btn upload-product-bg pull-right " type="button">
          My Ads <span class="badge">{{ my_ads }}</span>&nbsp;|&nbsp;<a href="{% url 'logout' %}">logout</a>
                &nbsp;|&nbsp;<a href="{% url 'edit_profile' %}">update profile</a>
                 &nbsp;|&nbsp;<a href="{% url 'profile_preview' %}">profile preview</a>
        </button>
      </ul>


        <div class="col-sm-12">
               <h3 class="text-center upload-product-bg how-to-create-ad">Create a free Ad in 30 Seconds</h3><br>
            <div class="col-sm-4">

            <span class="btn upload-product-bg  step1">Step 1:</span>
            Choose a category<br><br>

            <ul class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><a href="{% url 'create_product_step_1' wedding_category.id %}" class="btn upload-product-bg">{{ wedding_category }}</a></li>
            <li><a href="{% url 'create_product_step_1' love_category.id %}" class="btn upload-product-bg2">{{ love_category }}</a></li>
            <li><a href="{% url 'create_product_step_1' birthday_category.id %}" class="btn upload-product-bg">{{ birthday_category }}</a></li>
           <li><a href="{% url 'create_product_step_1' anniversary_category.id %}" class="btn upload-product-bg2">{{ anniversary_category }}</a></li>
           <li><a href="{% url 'create_product_step_1' graduation_category.id %}" class="btn upload-product-bg">{{ graduation_category }}</a></li>

          </ul>
        </ul>
            </div>
            <div class="col-sm-4">
            <span class="btn upload-product-bg  step2">Step 2:</span>
            Add location details<br><br>
            {% if latest %}
            <a href="{% url 'create_product_step_2' latest.id %}">{{ latest }}</a> &nbsp;&nbsp;|&nbsp;&nbsp;
                {{ latest.get_location_state_display }}&nbsp;&nbsp;|&nbsp;&nbsp;
                {{ latest.get_image_state_display }}
            {% endif %}

            </div>

           <div class="col-sm-4">
            <span class="btn upload-product-bg step3">Step 3:</span>
            Add more images of the product<br><br>
            {% if latest %}
            <a href="{% url 'create_product_step_3' latest.id %}">Add images</a>
            {% endif %}
            </div>
        </div>
        <div class="col-sm-12">
            <h3 class="text-center upload-product-bg how-to-create-ad">My Ads</h3>
            {% if ads %}
            <table class="table table-hover table-striped table-bordered">
                <thead>
                <th data-field="id" class="col-xs-2">Product</th>
                <th data-field="price" class="col-xs-2">Profile</th>
                <th data-field="price" class="col-xs-2"><i class="glyphicon glyphicon-star"></i>&nbsp;&nbsp;Location</th>
                <th data-field="price" class="col-xs-2"><i class="glyphicon glyphicon-star"></i>&nbsp;&nbsp;Images</th>

                </thead>
                {% for ad in ads %}
                <tr>
                    <td>
                        <a href="/pata_gift/product_details/{{ ad.id }}">{{ ad.product_name }}</a>
                    </td>
                    <td>
                        <img class="img img-circle" src="{{ ad.product_image.url }}" height="50" width="50">
                    </td>
                    <td>
                        {% if ad.location_state == 1 %}
                       <span class="text-success">{{ ad.get_location_state_display }}</span>
                        {% else %}
                        <span class="text-danger">{{ ad.get_location_state_display }}</span>
                        <a href="{% url 'create_product_step_2' ad.id %}">add</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if ad.image_state == 1 %}
                       <span class="text-success">{{ ad.get_image_state_display }}</span>&nbsp;&nbsp;|&nbsp;
                        <div class="btn-group">
                                <button data-toggle="dropdown" class="btn btn-xs dropdown-toggle" data-original-title="" title="">
                                  Manage
                                  <span class="caret">
                                  </span>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                  <li>
                                    <a class="text-info" href="/pata_gift/edit/{{ ad.id }}">Edit</a>
                                  </li>
                                  <li>
                                    <a class="text-danger" href="/pata_gift/delete/{{ ad.id }}">Delete</a>
                                  </li>
                                </ul>
                        </div>
                        {% else %}
                        <span class="text-danger">{{ ad.get_image_state_display }}</span>&nbsp;&nbsp;|&nbsp;
                        <a href="{% url 'create_product_step_3' ad.id %}">add</a>
                        <div class="btn-group">
                                <button data-toggle="dropdown" class="btn btn-xs dropdown-toggle" data-original-title="" title="">
                                  Manage
                                  <span class="caret">
                                  </span>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                  <li>
                                    <a class="text-info" href="/pata_gift/edit/{{ ad.id }}">Edit</a>
                                  </li>
                                  <li>
                                    <a class="text-danger" href="/pata_gift/delete/{{ ad.id }}">Delete</a>
                                  </li>
                                </ul>
                        </div>
                        {% endif %}
                    </td>
                </tr>
                 {% endfor %}
            </table>


            {% else %}
            <h4>You have not posted any ads</h4>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/pata_gift/reg_form_error.html
<div id="firstNameHelpDiv">
    Your first name as it appears in your national ID card
</div>
<div id="secondNameHelpDiv">
    Your second name as it appears in your national ID card
</div>
<div id="email1HelpDiv">
    Your valid email
</div>
<div id="incomeHelpDiv">
    Your income as per the official documents
</div>